{{- if and .Values.observability.prometheus.enabled .Values.observability.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tlapix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tlapix.labels" . | nindent 4 }}
    {{- with .Values.observability.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "tlapix.centralSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.observability.prometheus.serviceMonitor.interval }}
      path: /metrics
{{- end }}
