server {
    listen 443 ssl;
    server_name expiring.tlapix-demo.local;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        return 200 '{"server": "expiring", "status": "cert-about-to-expire"}';
        add_header Content-Type application/json;
    }
}
